"""device_credential seq (registration order tie-break)

슬라이스 63 — PgDeviceStore.list_for_user 동률 정렬 tie-break용 등록 순번(IDENTITY). slice 54
InMemoryDeviceStore.seq와 parity(같은 created_at/last_used_at 충돌 시 등록 순서로 결정론적
2차 정렬). 단일 컬럼 ORDER BY의 불안정 순서(slice 54가 남긴 Pg 한계) 해소.

기존 행: `ADD COLUMN ... GENERATED BY DEFAULT AS IDENTITY`는 기존 행을 물리적 순서로 백필
(상대 seq는 임의이나 이후 안정) + 신규 register는 DB 자동 증가 → 이후 등록 순서 결정론.
SELECT엔 미노출(ORDER BY 전용·DeviceInfo에 없음). 운영 시 populated 테이블 ADD는 테이블
재작성(ACCESS EXCLUSIVE) — device_credential은 소규모라 수용.

Revision ID: c9d0e1f2a3b4
Revises: b8c9d0e1f2a3
Create Date: 2026-06-04 06:00:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9d0e1f2a3b4"
down_revision: str | None = "b8c9d0e1f2a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "device_credential",
        sa.Column("seq", sa.BigInteger(), sa.Identity(), nullable=False),
    )


def downgrade() -> None:
    op.drop_column("device_credential", "seq")
