"""activity dialogue assessment timeseries domains

Revision ID: bb30b816083d
Revises: 1551744048aa
Create Date: 2026-05-29 02:24:59.991334
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb30b816083d"
down_revision: str | None = "1551744048aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attempt_event",
        sa.Column("event_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("event_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("problem_id", sa.Uuid(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "문제읽기",
                "조건분석",
                "그래프그리기",
                "계산",
                "지움",
                "막힘",
                "힌트요청",
                "답입력",
                name="event_type_enum",
            ),
            nullable=True,
        ),
        sa.Column("event_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("event_id", "event_at", name=op.f("pk_attempt_event")),
    )
    op.create_table(
        "concept_mastery_history",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("concept_id", sa.Uuid(), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mastery", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint(
            "user_id", "concept_id", "measured_at", name=op.f("pk_concept_mastery_history")
        ),
    )
    op.create_table(
        "daily_learning_metrics",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("metric_date", sa.Date(), nullable=False),
        sa.Column("minutes_active", sa.Integer(), nullable=True),
        sa.Column("problems_attempted", sa.Integer(), nullable=True),
        sa.Column("problems_correct", sa.Integer(), nullable=True),
        sa.Column("socratic_turns", sa.Integer(), nullable=True),
        sa.Column(
            "concepts_practiced",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("avg_focus_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.PrimaryKeyConstraint("user_id", "metric_date", name=op.f("pk_daily_learning_metrics")),
    )
    op.create_table(
        "problem_solve_time_distribution",
        sa.Column("problem_id", sa.Uuid(), nullable=False),
        sa.Column(
            "persona",
            postgresql.ENUM(
                "A_일반고고3",
                "B_자사고N수",
                "C_검정고시N수",
                "D_학종고2",
                "E_홈스쿨링영재",
                name="persona_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("p10_seconds", sa.Integer(), nullable=True),
        sa.Column("p50_seconds", sa.Integer(), nullable=True),
        sa.Column("p90_seconds", sa.Integer(), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint(
            "problem_id", "persona", "measured_at", name=op.f("pk_problem_solve_time_distribution")
        ),
    )
    op.create_table(
        "user_behavior_metrics",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("metric_name", sa.String(length=50), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metric_value", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.PrimaryKeyConstraint(
            "user_id", "metric_name", "measured_at", name=op.f("pk_user_behavior_metrics")
        ),
    )
    op.create_table(
        "assessment",
        sa.Column(
            "assessment_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "assessment_type",
            sa.Enum(
                "초기진단",
                "주간진단",
                "단원진단",
                "실전모의고사",
                "D-100예측",
                name="assessment_type_enum",
            ),
            nullable=True,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_grade", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("estimated_score", sa.Integer(), nullable=True),
        sa.Column("estimated_percentile", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("target_university_id", sa.Uuid(), nullable=True),
        sa.Column("admission_probability", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column(
            "concept_diagnosis",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "pattern_diagnosis",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "weak_points",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "strong_points",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "recommended_path",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "mental_phase",
            sa.Enum(
                "D_100_PLUS",
                "D_100_50",
                "D_50_30",
                "D_30_7",
                "D_7_0",
                "평상시",
                name="mental_phase_enum",
            ),
            nullable=True,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user_profile.user_id"], name=op.f("fk_assessment_user_id_user_profile")
        ),
        sa.PrimaryKeyConstraint("assessment_id", name=op.f("pk_assessment")),
    )
    op.create_table(
        "learning_session",
        sa.Column(
            "session_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "session_type",
            sa.Enum(
                "자유학습",
                "실전모의고사",
                "단원집중",
                "약점보완",
                "AI추천",
                name="session_type_enum",
            ),
            nullable=True,
        ),
        sa.Column("target_concept_id", sa.Uuid(), nullable=True),
        sa.Column("problems_attempted", sa.Integer(), nullable=True),
        sa.Column("problems_completed", sa.Integer(), nullable=True),
        sa.Column("problems_correct", sa.Integer(), nullable=True),
        sa.Column("focus_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("engagement_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column(
            "device_used",
            postgresql.ENUM(
                "아이패드", "iPhone", "안드로이드폰", "PC", name="device_enum", create_type=False
            ),
            nullable=True,
        ),
        sa.Column("network_type", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_profile.user_id"],
            name=op.f("fk_learning_session_user_id_user_profile"),
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_learning_session")),
    )
    op.create_index(
        "idx_session_user",
        "learning_session",
        ["user_id", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "problem_attempt",
        sa.Column(
            "attempt_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("problem_id", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("student_answer", sa.Text(), nullable=True),
        sa.Column("confidence_self_reported", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column(
            "attempt_mode",
            sa.Enum("자유풀이", "Socratic대화", "힌트제공", "풀이공개", name="attempt_mode_enum"),
            nullable=True,
        ),
        sa.Column("used_socratic", sa.Boolean(), nullable=True),
        sa.Column("used_hint", sa.Boolean(), nullable=True),
        sa.Column("used_solution_view", sa.Boolean(), nullable=True),
        sa.Column("handwriting_uri", sa.Text(), nullable=True),
        sa.Column("ocr_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("stuck_at_step", sa.Integer(), nullable=True),
        sa.Column("stuck_at_concept_id", sa.Uuid(), nullable=True),
        sa.Column("time_vs_expected", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column(
            "step_times",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problem.problem_id"],
            name=op.f("fk_problem_attempt_problem_id_problem"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["learning_session.session_id"],
            name=op.f("fk_problem_attempt_session_id_learning_session"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_profile.user_id"],
            name=op.f("fk_problem_attempt_user_id_user_profile"),
        ),
        sa.PrimaryKeyConstraint("attempt_id", name=op.f("pk_problem_attempt")),
    )
    op.create_index("idx_attempt_problem", "problem_attempt", ["problem_id"], unique=False)
    op.create_index(
        "idx_attempt_stuck",
        "problem_attempt",
        ["stuck_at_concept_id"],
        unique=False,
        postgresql_where=sa.text("stuck_at_concept_id IS NOT NULL"),
    )
    op.create_index(
        "idx_attempt_user",
        "problem_attempt",
        ["user_id", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "dialogue",
        sa.Column(
            "dialogue_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("attempt_id", sa.Uuid(), nullable=True),
        sa.Column("problem_id", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "resolution",
            sa.Enum(
                "학생자력해결",
                "Socratic유도성공",
                "힌트필요",
                "풀이공개로종결",
                "포기",
                name="resolution_enum",
            ),
            nullable=True,
        ),
        sa.Column("total_turns", sa.Integer(), nullable=True),
        sa.Column("student_turns", sa.Integer(), nullable=True),
        sa.Column("assistant_turns", sa.Integer(), nullable=True),
        sa.Column("model_used", sa.String(length=50), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("estimated_cost_usd", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("student_rating", sa.Integer(), nullable=True),
        sa.Column("auto_quality_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column(
            "flagged_for_review", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["problem_attempt.attempt_id"],
            name=op.f("fk_dialogue_attempt_id_problem_attempt"),
        ),
        sa.ForeignKeyConstraint(
            ["problem_id"], ["problem.problem_id"], name=op.f("fk_dialogue_problem_id_problem")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user_profile.user_id"], name=op.f("fk_dialogue_user_id_user_profile")
        ),
        sa.PrimaryKeyConstraint("dialogue_id", name=op.f("pk_dialogue")),
    )
    op.create_index("idx_dialogue_problem", "dialogue", ["problem_id"], unique=False)
    op.create_index(
        "idx_dialogue_user",
        "dialogue",
        ["user_id", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "dialogue_turn",
        sa.Column(
            "turn_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("dialogue_id", sa.Uuid(), nullable=True),
        sa.Column("turn_order", sa.Integer(), nullable=False),
        sa.Column(
            "spoken_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "role", sa.Enum("student", "assistant", "system", name="turn_role_enum"), nullable=True
        ),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "content_type",
            sa.Enum("텍스트", "수식", "이미지", "혼합", name="content_type_enum"),
            nullable=True,
        ),
        sa.Column(
            "socratic_strategy",
            sa.Enum(
                "조건확인",
                "예시제시",
                "반례제시",
                "단계분해",
                "유사문제",
                "그래프그리기제안",
                name="socratic_strategy_enum",
            ),
            nullable=True,
        ),
        sa.Column("targeted_step", sa.Integer(), nullable=True),
        sa.Column("targeted_concept_id", sa.Uuid(), nullable=True),
        sa.Column(
            "student_intent",
            sa.Enum("답시도", "질문", "막힘표현", "포기", "이해확인", name="student_intent_enum"),
            nullable=True,
        ),
        sa.Column("student_understanding_signal", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("image_uri", sa.Text(), nullable=True),
        sa.Column("image_analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["dialogue_id"],
            ["dialogue.dialogue_id"],
            name=op.f("fk_dialogue_turn_dialogue_id_dialogue"),
        ),
        sa.PrimaryKeyConstraint("turn_id", name=op.f("pk_dialogue_turn")),
        sa.UniqueConstraint("dialogue_id", "turn_order", name=op.f("uq_dialogue_turn_dialogue_id")),
    )
    op.create_index(
        "idx_turn_dialogue", "dialogue_turn", ["dialogue_id", "turn_order"], unique=False
    )
    # TimescaleDB hypertable 변환(§6·§8·§9 정본 DDL). timescaledb 확장이 설치된 환경에서만
    # 적용 — 미설치 PG(개발·CI)에서는 일반 테이블로 남아 검증 가능. if_not_exists로 멱등.
    # 5종 모두 시간 컬럼이 PK에 포함돼 hypertable UNIQUE 제약을 만족(파티션 키 포함 규칙).
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'timescaledb') THEN
                PERFORM create_hypertable('attempt_event', 'event_at',
                    chunk_time_interval => INTERVAL '1 day', if_not_exists => TRUE);
                PERFORM create_hypertable('concept_mastery_history', 'measured_at',
                    chunk_time_interval => INTERVAL '7 days', if_not_exists => TRUE);
                PERFORM create_hypertable('daily_learning_metrics', 'metric_date',
                    chunk_time_interval => INTERVAL '30 days', if_not_exists => TRUE);
                PERFORM create_hypertable('problem_solve_time_distribution', 'measured_at',
                    chunk_time_interval => INTERVAL '7 days', if_not_exists => TRUE);
                PERFORM create_hypertable('user_behavior_metrics', 'measured_at',
                    chunk_time_interval => INTERVAL '7 days', if_not_exists => TRUE);
            END IF;
        END
        $$;
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_turn_dialogue", table_name="dialogue_turn")
    op.drop_table("dialogue_turn")
    op.drop_index("idx_dialogue_user", table_name="dialogue")
    op.drop_index("idx_dialogue_problem", table_name="dialogue")
    op.drop_table("dialogue")
    op.drop_index("idx_attempt_user", table_name="problem_attempt")
    op.drop_index(
        "idx_attempt_stuck",
        table_name="problem_attempt",
        postgresql_where=sa.text("stuck_at_concept_id IS NOT NULL"),
    )
    op.drop_index("idx_attempt_problem", table_name="problem_attempt")
    op.drop_table("problem_attempt")
    op.drop_index("idx_session_user", table_name="learning_session")
    op.drop_table("learning_session")
    op.drop_table("assessment")
    op.drop_table("user_behavior_metrics")
    op.drop_table("problem_solve_time_distribution")
    op.drop_table("daily_learning_metrics")
    op.drop_table("concept_mastery_history")
    op.drop_table("attempt_event")
    # 이 마이그레이션이 새로 만든 native ENUM 정리(공유 device_enum·persona_enum은 배치1 user
    # 도메인 소유 → 여기서 안 떨굼·create_type=False로 재생성도 안 했음). checkfirst로 멱등.
    # hypertable은 drop_table 시 chunk까지 자동 정리되므로 추가 작업 불필요.
    for _enum_name in (
        "event_type_enum",
        "session_type_enum",
        "attempt_mode_enum",
        "resolution_enum",
        "turn_role_enum",
        "content_type_enum",
        "socratic_strategy_enum",
        "student_intent_enum",
        "assessment_type_enum",
        "mental_phase_enum",
    ):
        postgresql.ENUM(name=_enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
