"""initial problem domain — Problem 도메인(§3.1·§3.2) 테이블·ENUM 최초 생성.

도메인1 Problem 영속 레이어의 첫 마이그레이션: problem·problem_step·problem_relation
3테이블 + PG native ENUM 11종(source_type_enum 등) + 인덱스(GIN 4종 포함). downgrade는
테이블과 함께 ENUM 타입까지 명시 drop한다 — create_table이 자동 생성한 PG enum은
drop_table로 사라지지 않아, 안 떨구면 재-upgrade가 "type already exists"로 깨진다(alembic
native-enum 표준 갭). 로컬 PostgreSQL 16에서 upgrade/downgrade 왕복·재-upgrade·alembic
check(무드리프트) 검증됨.

Revision ID: 4c6d083dfeef
Revises:
Create Date: 2026-05-28 18:01:47.115248
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c6d083dfeef"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "problem",
        sa.Column(
            "problem_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("external_id", sa.String(length=64), nullable=True),
        sa.Column("slug", sa.String(length=128), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum(
                "평가원",
                "EBS",
                "AIHub",
                "교육청학평",
                "사설모의고사",
                "자체생성",
                "사용자자작",
                "교과서",
                name="source_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("source_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "exam_type",
            sa.Enum("수능", "모평", "학평", "EBS교재", "N제", "자체생성", name="exam_type_enum"),
            nullable=True,
        ),
        sa.Column("exam_year", sa.Integer(), nullable=True),
        sa.Column("exam_month", sa.Integer(), nullable=True),
        sa.Column("problem_number", sa.Integer(), nullable=True),
        sa.Column("exam_authority_weight", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column(
            "curriculum_version",
            sa.Enum("2009_REVISION", "2015_REVISION", "2022_REVISION", name="curriculum_enum"),
            nullable=False,
        ),
        sa.Column("valid_from_year", sa.Integer(), nullable=False),
        sa.Column("valid_to_year", sa.Integer(), nullable=True),
        sa.Column(
            "subject",
            sa.Enum("공통", "미적분", "확통", "기하", "인공지능수학", name="subject_enum"),
            nullable=False,
        ),
        sa.Column("unit_codes", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "question_format",
            sa.Enum("객관식", "단답형", "합답형", "서술형", name="question_format_enum"),
            nullable=True,
        ),
        sa.Column("points", sa.Integer(), nullable=True),
        sa.Column(
            "answer_format",
            sa.Enum("자연수", "분수", "실수", "식", name="answer_format_enum"),
            nullable=True,
        ),
        sa.Column("answer_constraint", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("answer_transform", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("question_text", sa.Text(), nullable=True),
        sa.Column("question_text_md", sa.Text(), nullable=True),
        sa.Column("question_image_uri", sa.Text(), nullable=True),
        sa.Column("choices", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("answer_explanation", sa.Text(), nullable=True),
        sa.Column("multiple_answers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "signature_patterns",
            postgresql.ARRAY(
                sa.Enum(
                    "CONDITION_LIST",
                    "COMPOSITE_DIFFERENTIABILITY",
                    "INDUCTIVE_SEQUENCE",
                    "DEFINED_INTEGRAL_FUNCTION",
                    "FUNCTION_COUNT",
                    "GRAPH_SHAPE_INFERENCE",
                    "CASE_ANALYSIS_DEEP",
                    "CROSS_UNIT_FUSION",
                    "NATURAL_NUMBER_TRANSFORM",
                    "COMPOUND_CHOICES",
                    name="signature_pattern_enum",
                )
            ),
            server_default=sa.text("'{}'::signature_pattern_enum[]"),
            nullable=False,
        ),
        sa.Column(
            "has_condition_list", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("condition_count", sa.Integer(), nullable=True),
        sa.Column(
            "conditions_parsed",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("has_visual", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "visual_type",
            postgresql.ARRAY(sa.Enum("그래프", "도형", "표", "좌표평면", name="visual_type_enum")),
            server_default=sa.text("'{}'::visual_type_enum[]"),
            nullable=False,
        ),
        sa.Column("visual_complexity", sa.Integer(), nullable=True),
        sa.Column("difficulty_overall", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("diff_calculation", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("diff_interpretation", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("diff_case_analysis", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("diff_visual", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("diff_integration", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("historical_correct_rate", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("rate_top_grade", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("rate_mid_grade", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("rate_low_grade", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("expected_solve_seconds", sa.Integer(), nullable=True),
        sa.Column("expected_solve_seconds_p90", sa.Integer(), nullable=True),
        sa.Column("persona_fit", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ebs_linked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("ebs_source", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_cross_unit", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "cross_unit_pairs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "requires_graph_sketch", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("sketch_step_count", sa.Integer(), nullable=True),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "keywords",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("is_premium", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("publish_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "review_status",
            sa.Enum("pending", "approved", "rejected", name="review_status_enum"),
            nullable=True,
        ),
        sa.Column("review_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.PrimaryKeyConstraint("problem_id", name=op.f("pk_problem")),
        sa.UniqueConstraint("external_id", name=op.f("uq_problem_external_id")),
        sa.UniqueConstraint("slug", name=op.f("uq_problem_slug")),
    )
    op.create_index(
        "idx_problem_curriculum", "problem", ["curriculum_version", "valid_from_year"], unique=False
    )
    op.create_index("idx_problem_difficulty", "problem", ["difficulty_overall"], unique=False)
    op.create_index(
        "idx_problem_exam", "problem", ["exam_type", "exam_year", "exam_month"], unique=False
    )
    op.create_index(
        "idx_problem_keywords", "problem", ["keywords"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "idx_problem_persona_fit", "problem", ["persona_fit"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "idx_problem_signature",
        "problem",
        ["signature_patterns"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("idx_problem_subject_unit", "problem", ["subject", "unit_codes"], unique=False)
    op.create_index("idx_problem_tags", "problem", ["tags"], unique=False, postgresql_using="gin")
    op.create_table(
        "problem_relation",
        sa.Column("parent_problem_id", sa.Uuid(), nullable=False),
        sa.Column("related_problem_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relation_type",
            sa.Enum("변형", "유사", "선수", "심화", "대조", name="relation_type_enum"),
            nullable=False,
        ),
        sa.Column("similarity_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_problem_id"],
            ["problem.problem_id"],
            name=op.f("fk_problem_relation_parent_problem_id_problem"),
        ),
        sa.ForeignKeyConstraint(
            ["related_problem_id"],
            ["problem.problem_id"],
            name=op.f("fk_problem_relation_related_problem_id_problem"),
        ),
        sa.PrimaryKeyConstraint(
            "parent_problem_id",
            "related_problem_id",
            "relation_type",
            name=op.f("pk_problem_relation"),
        ),
    )
    op.create_table(
        "problem_step",
        sa.Column(
            "step_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("problem_id", sa.Uuid(), nullable=True),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column(
            "step_type",
            sa.Enum(
                "조건해석", "케이스분류", "그래프스케치", "계산", "검산", name="step_type_enum"
            ),
            nullable=True,
        ),
        sa.Column("step_title", sa.String(length=200), nullable=True),
        sa.Column("socratic_prompt", sa.Text(), nullable=True),
        sa.Column("expected_answer", sa.Text(), nullable=True),
        sa.Column(
            "common_mistakes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["problem_id"], ["problem.problem_id"], name=op.f("fk_problem_step_problem_id_problem")
        ),
        sa.PrimaryKeyConstraint("step_id", name=op.f("pk_problem_step")),
        sa.UniqueConstraint("problem_id", "step_order", name=op.f("uq_problem_step_problem_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("problem_step")
    op.drop_table("problem_relation")
    op.drop_index("idx_problem_tags", table_name="problem", postgresql_using="gin")
    op.drop_index("idx_problem_subject_unit", table_name="problem")
    op.drop_index("idx_problem_signature", table_name="problem", postgresql_using="gin")
    op.drop_index("idx_problem_persona_fit", table_name="problem", postgresql_using="gin")
    op.drop_index("idx_problem_keywords", table_name="problem", postgresql_using="gin")
    op.drop_index("idx_problem_exam", table_name="problem")
    op.drop_index("idx_problem_difficulty", table_name="problem")
    op.drop_index("idx_problem_curriculum", table_name="problem")
    op.drop_table("problem")
    # 네이티브 ENUM 타입 정리 — create_table이 자동 생성한 PG enum은 drop_table로 사라지지
    # 않으므로 명시 drop한다(안 떨구면 재-upgrade가 "type already exists"로 깨짐 — alembic
    # native-enum 표준 갭). 11종(persona_fit은 JSONB라 persona_enum 미생성). checkfirst로 멱등.
    for _enum_name in (
        "source_type_enum",
        "exam_type_enum",
        "curriculum_enum",
        "subject_enum",
        "question_format_enum",
        "answer_format_enum",
        "signature_pattern_enum",
        "visual_type_enum",
        "review_status_enum",
        "step_type_enum",
        "relation_type_enum",
    ):
        postgresql.ENUM(name=_enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
