"""concept provenance user curriculum textbook domains

Revision ID: 1551744048aa
Revises: 4c6d083dfeef
Create Date: 2026-05-28 22:23:53.953108
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1551744048aa"
down_revision: str | None = "4c6d083dfeef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "concept",
        sa.Column(
            "concept_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name_ko", sa.String(length=200), nullable=False),
        sa.Column("name_en", sa.String(length=200), nullable=True),
        sa.Column("aliases", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "level",
            sa.Enum("단원", "소단원", "세부개념", name="concept_level_enum"),
            nullable=False,
        ),
        sa.Column("parent_concept_id", sa.Uuid(), nullable=True),
        sa.Column(
            "subject",
            sa.Enum("공통", "미적분", "확통", "기하", "인공지능수학", name="subject_enum"),
            nullable=True,
        ),
        sa.Column(
            "curriculum_version",
            sa.Enum("2009_REVISION", "2015_REVISION", "2022_REVISION", name="curriculum_enum"),
            nullable=True,
        ),
        sa.Column("grade_introduced", sa.Integer(), nullable=True),
        sa.Column("semester_introduced", sa.Integer(), nullable=True),
        sa.Column(
            "is_signature_korean", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "cognitive_type",
            postgresql.ARRAY(
                sa.Enum(
                    "DEFINITION",
                    "THEOREM",
                    "TECHNIQUE",
                    "PATTERN",
                    "VISUAL_REASONING",
                    name="cognitive_type_enum",
                )
            ),
            nullable=True,
        ),
        sa.Column("intrinsic_difficulty", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("exam_frequency", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("weight_in_curriculum", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("formal_definition", sa.Text(), nullable=True),
        sa.Column("intuitive_explanation", sa.Text(), nullable=True),
        sa.Column(
            "common_misconceptions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("embedding_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["parent_concept_id"],
            ["concept.concept_id"],
            name=op.f("fk_concept_parent_concept_id_concept"),
        ),
        sa.PrimaryKeyConstraint("concept_id", name=op.f("pk_concept")),
        sa.UniqueConstraint("code", name=op.f("uq_concept_code")),
    )
    op.create_index("idx_concept_code", "concept", ["code"], unique=False)
    op.create_index("idx_concept_level", "concept", ["level", "subject"], unique=False)
    op.create_index("idx_concept_parent", "concept", ["parent_concept_id"], unique=False)
    op.create_table(
        "concept_fusion",
        sa.Column(
            "fusion_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column(
            "concept_ids",
            postgresql.ARRAY(sa.Uuid()),
            server_default=sa.text("'{}'::uuid[]"),
            nullable=False,
        ),
        sa.Column("fusion_difficulty", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("typical_question_pattern", sa.Text(), nullable=True),
        sa.Column("exemplar_problem_ids", postgresql.ARRAY(sa.Uuid()), nullable=True),
        sa.PrimaryKeyConstraint("fusion_id", name=op.f("pk_concept_fusion")),
    )
    op.create_table(
        "curriculum_entry",
        sa.Column("entry_id", sa.String(), nullable=False),
        sa.Column("concept_id", sa.String(), nullable=False),
        sa.Column("country_code", sa.String(), nullable=False),
        sa.Column("source_name", sa.String(), nullable=False),
        sa.Column("source_code", sa.String(), nullable=True),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("source_document", sa.String(), nullable=True),
        sa.Column(
            "license_id",
            sa.Enum(
                "KR-NCIC", "US-CCSS", "INT-IMO", "JP-MEXT", "GB-NC", name="curriculum_license_enum"
            ),
            nullable=False,
        ),
        sa.Column("introduced_grade", sa.Integer(), nullable=True),
        sa.Column("grade_band", sa.String(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("curriculum_revision", sa.String(), nullable=True),
        sa.Column("introduced_context", sa.Text(), nullable=True),
        sa.Column("domain_label", sa.String(), nullable=True),
        sa.Column("sub_domain_label", sa.String(), nullable=True),
        sa.Column(
            "required_depth",
            sa.Enum("awareness", "procedural", "conceptual", "mastery", name="required_depth_enum"),
            nullable=True,
        ),
        sa.Column("cognitive_level", sa.String(), nullable=True),
        sa.Column("is_assessed", sa.Boolean(), nullable=True),
        sa.Column("assessment_format", sa.String(), nullable=True),
        sa.Column("notation_local", sa.String(), nullable=True),
        sa.Column("terminology_local", sa.String(), nullable=True),
        sa.Column("notation_variants", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("prerequisite_concept_ids", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("followup_concept_ids", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("national_standard_codes", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("textbook_unit_refs", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("is_present", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("verified_by", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("entry_id", name=op.f("pk_curriculum_entry")),
        sa.UniqueConstraint(
            "concept_id", "country_code", name=op.f("uq_curriculum_entry_concept_id")
        ),
    )
    op.create_table(
        "textbook_mapping",
        sa.Column("isbn", sa.String(length=13), nullable=False),
        sa.Column("publisher", sa.String(), nullable=False),
        sa.Column("book_title", sa.String(), nullable=False),
        sa.Column("authors", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("grade", sa.Integer(), nullable=False),
        sa.Column("revision_year", sa.Integer(), nullable=False),
        sa.Column("curriculum_revision", sa.String(), nullable=True),
        sa.Column("tone_profile", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "source_urls",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("isolation_tag", sa.String(), nullable=False),
        sa.Column(
            "legal_review_status",
            sa.Enum("not_required", "pending", "cleared", name="legal_review_status_enum"),
            server_default=sa.text("'not_required'::legal_review_status_enum"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("isbn", name=op.f("pk_textbook_mapping")),
    )
    op.create_table(
        "user_profile",
        sa.Column(
            "user_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("email_hash", sa.String(length=64), nullable=True),
        sa.Column("nickname", sa.String(length=50), nullable=True),
        sa.Column("birth_year", sa.Integer(), nullable=True),
        sa.Column("gender", sa.String(length=32), nullable=True),
        sa.Column(
            "school_type",
            sa.Enum(
                "일반고",
                "자사고_전국",
                "자사고_광역",
                "외고",
                "국제고",
                "영재고",
                "과학고",
                "특성화고",
                "대안학교_인가",
                "대안학교_비인가",
                "홈스쿨링",
                "검정고시",
                name="school_type_enum",
            ),
            nullable=True,
        ),
        sa.Column("school_region", sa.String(length=64), nullable=True),
        sa.Column("school_id", sa.Uuid(), nullable=True),
        sa.Column("grade", sa.Integer(), nullable=True),
        sa.Column(
            "track_type",
            postgresql.ARRAY(
                sa.Enum(
                    "정시",
                    "수시학종",
                    "수시교과",
                    "수시논술",
                    "MMI",
                    "특기자",
                    "농어촌",
                    "특례",
                    name="track_type_enum",
                )
            ),
            nullable=True,
        ),
        sa.Column("target_universities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "target_major_category",
            sa.Enum(
                "의대",
                "약대",
                "치대",
                "한의대",
                "이공계",
                "인문계",
                "경상계",
                "예체능",
                name="major_category_enum",
            ),
            nullable=True,
        ),
        sa.Column("target_grade", sa.Integer(), nullable=True),
        sa.Column("target_score", sa.Integer(), nullable=True),
        sa.Column("target_exam_date", sa.Date(), nullable=True),
        sa.Column(
            "persona_primary",
            sa.Enum(
                "A_일반고고3",
                "B_자사고N수",
                "C_검정고시N수",
                "D_학종고2",
                "E_홈스쿨링영재",
                name="persona_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "persona_secondary",
            sa.Enum(
                "A_일반고고3",
                "B_자사고N수",
                "C_검정고시N수",
                "D_학종고2",
                "E_홈스쿨링영재",
                name="persona_enum",
            ),
            nullable=True,
        ),
        sa.Column("persona_confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column(
            "primary_device",
            sa.Enum("아이패드", "iPhone", "안드로이드폰", "PC", name="device_enum"),
            nullable=True,
        ),
        sa.Column("has_apple_pencil", sa.Boolean(), nullable=True),
        sa.Column(
            "note_app",
            sa.Enum("굿노트", "노타빌리티", "플렉슬", "없음", name="note_app_enum"),
            nullable=True,
        ),
        sa.Column("current_grade_estimate", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("current_grade_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "diagnostic_completed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("diagnostic_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uses_inkang", sa.Boolean(), nullable=True),
        sa.Column("inkang_provider", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("uses_offline_academy", sa.Boolean(), nullable=True),
        sa.Column("monthly_education_spend", sa.Integer(), nullable=True),
        sa.Column(
            "subscription_tier",
            sa.Enum("free", "basic", "premium", name="subscription_tier_enum"),
            nullable=True,
        ),
        sa.Column("subscription_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("subscription_renewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_minor", sa.Boolean(), nullable=True),
        sa.Column("parent_consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("parent_email_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "accessibility_needs",
            postgresql.ARRAY(
                sa.Enum(
                    "시각약자", "색약", "큰글씨", "음성안내", "시간연장", name="accessibility_enum"
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_profile")),
        sa.UniqueConstraint("email_hash", name=op.f("uq_user_profile_email_hash")),
    )
    op.create_index(
        "idx_user_active", "user_profile", ["is_active", "last_active_at"], unique=False
    )
    op.create_index("idx_user_persona", "user_profile", ["persona_primary"], unique=False)
    op.create_index("idx_user_school", "user_profile", ["school_type", "grade"], unique=False)
    op.create_index("idx_user_target", "user_profile", ["target_major_category"], unique=False)
    op.create_table(
        "concept_edge",
        sa.Column(
            "edge_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("from_concept_id", sa.Uuid(), nullable=False),
        sa.Column("to_concept_id", sa.Uuid(), nullable=False),
        sa.Column(
            "edge_type",
            sa.Enum(
                "PREREQUISITE",
                "COMPOSED_OF",
                "ANALOGOUS_TO",
                "EXTENDS",
                "CONTRASTS",
                name="edge_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("edge_strength", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("typical_gap_signal", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["from_concept_id"],
            ["concept.concept_id"],
            name=op.f("fk_concept_edge_from_concept_id_concept"),
        ),
        sa.ForeignKeyConstraint(
            ["to_concept_id"],
            ["concept.concept_id"],
            name=op.f("fk_concept_edge_to_concept_id_concept"),
        ),
        sa.PrimaryKeyConstraint("edge_id", name=op.f("pk_concept_edge")),
        sa.UniqueConstraint(
            "from_concept_id",
            "to_concept_id",
            "edge_type",
            name=op.f("uq_concept_edge_from_concept_id"),
        ),
    )
    op.create_index(
        "idx_concept_edge_from", "concept_edge", ["from_concept_id", "edge_type"], unique=False
    )
    op.create_index(
        "idx_concept_edge_to", "concept_edge", ["to_concept_id", "edge_type"], unique=False
    )
    op.create_table(
        "content_provenance",
        sa.Column(
            "provenance_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("problem_id", sa.Uuid(), nullable=True),
        sa.Column(
            "original_source",
            sa.Enum(
                "평가원",
                "EBS",
                "AIHub",
                "교육청학평",
                "사설모의고사",
                "자체생성",
                "사용자자작",
                "교과서",
                name="source_type_enum",
            ),
            nullable=True,
        ),
        sa.Column("original_reference", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "generation_type",
            sa.Enum(
                "ORIGINAL",
                "VARIANT_NUMBER",
                "VARIANT_STRUCTURE",
                "VARIANT_CONTEXT",
                "COMPOSED",
                "FULLY_GENERATED",
                name="generation_type_enum",
            ),
            nullable=True,
        ),
        sa.Column("transformation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("parent_problem_id", sa.Uuid(), nullable=True),
        sa.Column(
            "transformation_pipeline", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("auto_validation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("human_review", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column(
            "license",
            sa.Enum(
                "PUBLIC_DOMAIN",
                "EBS_LICENSED",
                "AIHUB_OPEN",
                "WHYMATH_GENERATED",
                "USER_GENERATED",
                "THIRD_PARTY_LICENSED",
                name="license_enum",
            ),
            nullable=True,
        ),
        sa.Column("copyright_notice", sa.Text(), nullable=True),
        sa.Column("usage_restrictions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["parent_problem_id"],
            ["problem.problem_id"],
            name=op.f("fk_content_provenance_parent_problem_id_problem"),
        ),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problem.problem_id"],
            name=op.f("fk_content_provenance_problem_id_problem"),
        ),
        sa.PrimaryKeyConstraint("provenance_id", name=op.f("pk_content_provenance")),
    )
    op.create_index(
        "idx_provenance_parent", "content_provenance", ["parent_problem_id"], unique=False
    )
    op.create_index("idx_provenance_problem", "content_provenance", ["problem_id"], unique=False)
    op.create_index(
        "idx_provenance_source", "content_provenance", ["original_source"], unique=False
    )
    op.create_table(
        "problem_concept",
        sa.Column("problem_id", sa.Uuid(), nullable=False),
        sa.Column("concept_id", sa.Uuid(), nullable=False),
        sa.Column("relevance", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column(
            "role",
            sa.Enum("PRIMARY", "SUPPORTING", "IMPLICIT", "TESTED", name="concept_role_enum"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concept.concept_id"],
            name=op.f("fk_problem_concept_concept_id_concept"),
        ),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problem.problem_id"],
            name=op.f("fk_problem_concept_problem_id_problem"),
        ),
        sa.PrimaryKeyConstraint(
            "problem_id", "concept_id", "role", name=op.f("pk_problem_concept")
        ),
    )
    op.create_index(
        "idx_problem_concept_pc", "problem_concept", ["problem_id", "concept_id"], unique=False
    )
    op.create_table(
        "textbook_unit",
        sa.Column("unit_id", sa.String(), nullable=False),
        sa.Column("textbook_isbn", sa.String(length=13), nullable=False),
        sa.Column("parent_unit_id", sa.String(), nullable=True),
        sa.Column("unit_number", sa.String(), nullable=False),
        sa.Column("unit_title", sa.String(length=200), nullable=False),
        sa.Column("page_range", sa.String(), nullable=True),
        sa.Column("standard_codes", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("concept_ids", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("learning_objective_text", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_unit_id"],
            ["textbook_unit.unit_id"],
            name=op.f("fk_textbook_unit_parent_unit_id_textbook_unit"),
        ),
        sa.ForeignKeyConstraint(
            ["textbook_isbn"],
            ["textbook_mapping.isbn"],
            name=op.f("fk_textbook_unit_textbook_isbn_textbook_mapping"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("unit_id", name=op.f("pk_textbook_unit")),
    )
    op.create_table(
        "user_persona_history",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "persona",
            sa.Enum(
                "A_일반고고3",
                "B_자사고N수",
                "C_검정고시N수",
                "D_학종고2",
                "E_홈스쿨링영재",
                name="persona_enum",
            ),
            nullable=True,
        ),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("signals", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_profile.user_id"],
            name=op.f("fk_user_persona_history_user_id_user_profile"),
        ),
        sa.PrimaryKeyConstraint("user_id", "detected_at", name=op.f("pk_user_persona_history")),
    )
    op.create_table(
        "user_state_snapshot",
        sa.Column(
            "snapshot_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "snapshot_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("estimated_grade", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("estimated_score", sa.Integer(), nullable=True),
        sa.Column("estimated_percentile", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("concept_mastery", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("pattern_mastery", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "avg_solve_time_by_difficulty", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("time_management_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("consecutive_active_days", sa.Integer(), nullable=True),
        sa.Column("avg_session_quality", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("embedding_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_profile.user_id"],
            name=op.f("fk_user_state_snapshot_user_id_user_profile"),
        ),
        sa.PrimaryKeyConstraint("snapshot_id", name=op.f("pk_user_state_snapshot")),
    )
    op.create_index(
        "idx_snapshot_user_time",
        "user_state_snapshot",
        ["user_id", sa.literal_column("snapshot_at DESC")],
        unique=False,
    )
    op.create_table(
        "user_track_history",
        sa.Column(
            "history_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "changed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("track_before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("track_after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_profile.user_id"],
            name=op.f("fk_user_track_history_user_id_user_profile"),
        ),
        sa.PrimaryKeyConstraint("history_id", name=op.f("pk_user_track_history")),
    )
    op.create_table(
        "generation_log",
        sa.Column("log_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("problem_id", sa.Uuid(), nullable=True),
        sa.Column("provenance_id", sa.Uuid(), nullable=True),
        sa.Column("model_name", sa.String(length=64), nullable=True),
        sa.Column("prompt_template_id", sa.Uuid(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problem.problem_id"],
            name=op.f("fk_generation_log_problem_id_problem"),
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["content_provenance.provenance_id"],
            name=op.f("fk_generation_log_provenance_id_content_provenance"),
        ),
        sa.PrimaryKeyConstraint("log_id", name=op.f("pk_generation_log")),
    )
    op.create_index("idx_generation_problem", "generation_log", ["problem_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_generation_problem", table_name="generation_log")
    op.drop_table("generation_log")
    op.drop_table("user_track_history")
    op.drop_index("idx_snapshot_user_time", table_name="user_state_snapshot")
    op.drop_table("user_state_snapshot")
    op.drop_table("user_persona_history")
    op.drop_table("textbook_unit")
    op.drop_index("idx_problem_concept_pc", table_name="problem_concept")
    op.drop_table("problem_concept")
    op.drop_index("idx_provenance_source", table_name="content_provenance")
    op.drop_index("idx_provenance_problem", table_name="content_provenance")
    op.drop_index("idx_provenance_parent", table_name="content_provenance")
    op.drop_table("content_provenance")
    op.drop_index("idx_concept_edge_to", table_name="concept_edge")
    op.drop_index("idx_concept_edge_from", table_name="concept_edge")
    op.drop_table("concept_edge")
    op.drop_index("idx_user_target", table_name="user_profile")
    op.drop_index("idx_user_school", table_name="user_profile")
    op.drop_index("idx_user_persona", table_name="user_profile")
    op.drop_index("idx_user_active", table_name="user_profile")
    op.drop_table("user_profile")
    op.drop_table("textbook_mapping")
    op.drop_table("curriculum_entry")
    op.drop_table("concept_fusion")
    op.drop_index("idx_concept_parent", table_name="concept")
    op.drop_index("idx_concept_level", table_name="concept")
    op.drop_index("idx_concept_code", table_name="concept")
    op.drop_table("concept")
    # ### end Alembic commands ###
